
spring:
  profiles:
    active: dev

  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  level:
    com:
      zlsoft:
        dao: debug




server:
  port: 8088
